name: Swagger

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v1
    - name: setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs pygments pymdown-extensions
    - name: build mkdocs
      run: |
        mkdocs build --verbose -d build
    - name: Deploy on Github Pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: build